### PR TITLE
Add Application and ApplictionType controllers

### PR DESCRIPTION
**Pull request by agrare**
Add applications and application_types controllers

The modeling was originally added to core in https://github.com/ManageIQ/topological_inventory-core/pull/116

### CODE REVIEW

**Comment by agrare** [comment]
cc @gtanzillo @abellotti

**Comment by martinpovolny** [comment]
Oh, well. You could have pinged me. I actually started working on this one.

**Comment by martinpovolny** [comment]
But never mind. From the learning perspective, I can read ;-)

A question: why aren't you also creating subcollections for the other relations such as application_type/application? Is it somehow systematic? Or is it what you think will be needed?

**Comment by agrare** [comment]
> Oh, well. You could have pinged me. I actually started working on this one.

Oh sorry didn't know that, I was trying to unblock you haha

> A question: why aren't you also creating subcollections for the other relations such as application_type/application? Is it somehow systematic? Or is it what you think will be needed?

Do you mean why isn't there an application_types subcollection under the application route?  It is because application_type is a `belongs_to` on an `application` so you just get back a single `application_type_id`

Or do you mean why isn't there a `sources/application_types` using the `:has_many :through` relation?

**Comment by martinpovolny** [comment]
>  application_types subcollection under the application route?

I mean the other way round

**Comment by agrare** [comment]
These were just based on what I thought would be used, if you need to go from application_types to applications then we can add a route for it.

**Pull request merged**
