### PR TITLE
Rename ServiceParametersSet to ServicePlan

### PR DESCRIPTION
**Pull request by bdunne**
Depends on https://github.com/ManageIQ/topological_inventory-core/pull/17

### CODE REVIEW

**Comment by agrare** [comment]
@bdunne we're not worrying about breaking API changes => bumping the major version yet right

**Comment by bdunne** [comment]
No, I think we're sticking to v0.0 for now.  I briefly talked to @carbonin & @gtanzillo and think we should start versioning soon, but we have to figure out when.

**Comment by agrare** [comment]
@bdunne looks like the subcollection for service_plan on service_instance isn't working:
```
No route matches [GET] "/api/v0.0/service_instances/1/service_plan"
```

**Comment by bdunne** [comment]
@agrare It should be `/api/v0.0/service_instances/1/service_plans`

**Comment by agrare** [comment]
@bdunne Oh okay, it is a singular belongs_to so should it be plural?

**Comment by bdunne** [comment]
I see, a `ServiceInstance` `belongs_to` a `ServicePlan`, so it's not a (sub)collection, it's a sub-resource and I currently don't have any routes for sub-resources.

**Comment by agrare** [comment]
Okay its not related to this PR, this looks good to me

**Pull request merged**
